version: "3.7"
services:
  nginx:
    container_name: nginx
    hostname: 'basset.rocks'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
  jenkins:
    depends_on:
      - nginx
    container_name: jenkins
    privileged: true
    build:
      context: .
      dockerfile: dockerfiles/jenkins.dockerfile
    stdin_open: true
    tty: true
    command: ./home/launch_services.sh
    ports:
      - '9090:9090'
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        nginx['listen_port']=8081
    ports:
      - '8081:8081'
      - '8443:443'
    shm_size: '256m'