version: "3.7"
services:
  jenkins:
    container_name: jenkins
    privileged: true
    build:
      context: .
      dockerfile: dockerfiles/jenkins.dockerfile
    stdin_open: true
    tty: true
    ports:
      - '80:80'
      - '8080:8080'