version: "3.7"

volumes:
  dependency-track:

services:

  nginx-server:
    container_name: nginx-server
    hostname: 'basset.rocks'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'

  jenkins-server:
    depends_on:
      - nginx-server
    container_name: jenkins-server
    privileged: true
    build:
      context: .
      dockerfile: dockerfiles/jenkins.dockerfile

  gitlab-server:
    depends_on:
      - nginx-server
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        nginx['listen_port']=8081
    shm_size: '256m'

  dtrack-server:
    image: dependencytrack/apiserver
    container_name: dtrack-server
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8083:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped

  dtrack-app:
    image: dependencytrack/frontend
    container_name: dtrack-app
    depends_on:
      - dtrack-server
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=http://localhost:8083
      # - "OIDC_ISSUER="
      # - "OIDC_CLIENT_ID="
      # - "OIDC_SCOPE="
      # - "OIDC_FLOW="
      # - "OIDC_LOGIN_BUTTON_TEXT="
      # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "8084:8080"
    restart: unless-stopped

#  dtrack-server:
#    depends_on:
#      - nginx-server
#    image: dependencytrack/bundled
#    container_name: dtrack-server
#    ports:
#      - '8083:8080'
#    volumes:
#      - 'dependency-track:/data'
#    restart: unless-stopped